lagomba/src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="array")
     */
    private $items = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $order_time;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getItems(): ?array
    {
        return $this->items;
    }

    public function setItems(array $items): self
    {
        $this->items = $items;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZip(): ?int
    {
        return $this->zip;
    }

    public function setZip(int $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getOrderTime(): ?\DateTimeInterface
    {
        return $this->order_time;
    }

    public function setOrderTime(\DateTimeInterface $order_time): self
    {
        $this->order_time = $order_time;

        return $this;
    }
}

lagomba/src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\Order;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class OrdersController extends AbstractController
{
    /**
     * @Route("/orders", name="add_orders")
     */
    public function index(Request $request)
    {
        try {
            $session = $request->getSession();
            $user_id = $this->get('security.token_storage')->getToken()->getUser();

            $user_id = $user_id->getId();

            $user = new User();
            $user = $this->getDoctrine()->getRepository(User::class);

            $user = $user->find($user_id);

            $order = new Order();

            $cart = new Cart();

            $mushrooms = $session->get('cart');
            $total = number_format($cart->getItemTotal($mushrooms), 2);

            $order->setName($user->getName());
            $order->setItems($session->get('cart'));
            $order->setAddress($user->getAddress());
            $order->setCity($user->getCity());
            $order->setUserId($user->getId());
            $order->setZip($user->getZip());
            $order->setTotal($total);
            $order->setOrderTime(new \DateTime());

            $entityManage = $this->getDoctrine()->getManager();
            $entityManage->persist($order);
            $entityManage->flush();

            return $this->json(true);
        } catch (\Exception $exception) {
            return $this->render('error.html.twig', [
                'message' => $exception->getMessage(),
            ]);
        }
    }

    /**
     * @Route("/admin/orders", name="orders")
     */
    public function showOrders()
    {
        try {
            $orders = new Order();
            $orders = $this->getDoctrine()->getRepository(Order::class);

            $orders = $orders->findAll();

            return $this->render('orders/index.html.twig', [
                'orders' => $orders,
            ]);
        } catch (\Exception $exception) {
            return $this->render('error.html.twig', [
                'message' => $exception->getMessage(),
            ]);
        }
    }

    /**
     * @Route("/admin/remove-order/{id}", name="remove-order")
     *
     * @param mixed $id
     */
    public function removeOrder($id)
    {
        $em = $this->getDoctrine()->getManager();
        $order = $em->getRepository(Order::class)->find($id);

        if (!$order) {
            throw $this->createNotFoundException(
                'No record for the order with the id: '.$id
            );
        }

        $this->addFlash(
            'notice',
            'Order Deleted Successfully'
        );

        $em->remove($order);
        $em->flush();

        return $this->redirectToRoute('orders');
    }
}

lagomba/templates/orders/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Mushroom Orders
{% endblock %}

{% block body %}
<div class="container my-5">
    {% if app.flashes is defined %}
    {% for message in app.flashes('notice') %}
        <div class="row px-4" id="alert-message">
            <div class="col-12 alert alert-success" role="alert"">
                {{ message }}
            </div>
        </div>
    {% endfor %}
    {% endif %}
	{% if orders | length == 0 %}
		There are no orders
	{% endif %}
	<div class=" accordion" id="accordionExample">
	{% for order in orders %}
		<div class="card">
			<div class="card-header" id="headingOne{{order.id}}">
				<div class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne{{order.id}}" aria-expanded="true" aria-controls="collapseOne{{order.id}}">
					<span>Order ID: #{{ order.id }}</span>
					<span class="pull-right">Date:
						{{ order.orderTime | date('m.d.Y H:i:s') }}</span>
				</div>
			</div>

			<div id="collapseOne{{order.id}}" class="collapse" aria-labelledby="headingOne{{order.id}}" data-parent="#accordionExample">
				<div class="card-body">
                    <a href="/admin/remove-order/{{ order.id }}" class="btn btn-danger btn-sm pull-right"><i class="fa fa-trash"></i> Delete</a></td>
                    Shipping Address:
                    <br>
					{{ order.name }}
					<br>
					{{ order.address }}
					<br>
					{{ order.zip }}
                    {{ order.city }}
					<hr class="mb-2 w-100">
					Order:
					<div class="row">
						<table class="table table-hover">
							<thead>
								<tr>
									<th scope="col">Name</th>
									<th scope="col">Qty</th>
									<th scope="col">Unit Price</th>
									<th scope="col">Price</th>
								</tr>
							</thead>
							<tbody>

								{% for item in order.items %}
									<tr class="table">
										<td>{{ item.name }}</td>
										<td>{{ item.qty }}</td>
										<td>{{ item.unit_price | number_format(2, ',', '.') }}
											&#8364;</td>
										<td>{{ item.price | number_format(2, ',', '.') }}
											&#8364;</td>
									</tr>
                                {% endfor %}
                                <tr class="table">
                                    <td></td>
                                    <td></td>
                                    <td><b>Total : </b></td>
                                    <td>{{ order.total | number_format(2, ',', '.') }} &#8364;</td>
                                </tr>
                                <tr class="table">
                                    <td></td>
                                    <td></td>
                                    <td><b>Paid with : </b></td>
                                    <td><img src="https://www.paypalobjects.com/webstatic/de_DE/i/de-pp-logo-100px.png" border="0" alt="PayPal Logo" /></td>
                                </tr>
							</tbody>
						</table>
					</div>
				</div>
            </div>
		</div>
        {% endfor %}
        
	</div>
</div>
{% endblock %}